{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2a1228ae",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Extrayendo URLs...\n",
      "Page 1: 10 nuevas (10 acumuladas)\n",
      "Page 2: 10 nuevas (20 acumuladas)\n",
      "Page 3: 10 nuevas (30 acumuladas)\n",
      "Page 4: 10 nuevas (40 acumuladas)\n",
      "Page 5: 10 nuevas (50 acumuladas)\n",
      "Page 6: 10 nuevas (60 acumuladas)\n",
      "Page 7: 10 nuevas (70 acumuladas)\n",
      "Page 8: 10 nuevas (80 acumuladas)\n",
      "Page 9: 10 nuevas (90 acumuladas)\n",
      "Page 10: 10 nuevas (100 acumuladas)\n",
      "Page 11: 10 nuevas (110 acumuladas)\n",
      "Page 12: 10 nuevas (120 acumuladas)\n",
      "Page 13: 3 nuevas (123 acumuladas)\n",
      "Fin de paginación en page=14\n",
      "\n",
      "Total URLs únicas: 123\n",
      "[1/123]\n",
      "[2/123]\n",
      "[3/123]\n",
      "[4/123]\n",
      "[5/123]\n",
      "[6/123]\n",
      "[7/123]\n",
      "[8/123]\n",
      "[9/123]\n",
      "[10/123]\n",
      "[11/123]\n",
      "[12/123]\n",
      "[13/123]\n",
      "[14/123]\n",
      "[15/123]\n",
      "[16/123]\n",
      "[17/123]\n",
      "[18/123]\n",
      "[19/123]\n",
      "[20/123]\n",
      "[21/123]\n",
      "[22/123]\n",
      "[23/123]\n",
      "[24/123]\n",
      "[25/123]\n",
      "[26/123]\n",
      "[27/123]\n",
      "[28/123]\n",
      "[29/123]\n",
      "[30/123]\n",
      "[31/123]\n",
      "[32/123]\n",
      "[33/123]\n",
      "[34/123]\n",
      "[35/123]\n",
      "[36/123]\n",
      "[37/123]\n",
      "[38/123]\n",
      "[39/123]\n",
      "[40/123]\n",
      "[41/123]\n",
      "[42/123]\n",
      "[43/123]\n",
      "[44/123]\n",
      "[45/123]\n",
      "[46/123]\n",
      "[47/123]\n",
      "[48/123]\n",
      "[49/123]\n",
      "[50/123]\n",
      "[51/123]\n",
      "[52/123]\n",
      "[53/123]\n",
      "[54/123]\n",
      "[55/123]\n",
      "[56/123]\n",
      "[57/123]\n",
      "[58/123]\n",
      "[59/123]\n",
      "[60/123]\n",
      "[61/123]\n",
      "[62/123]\n",
      "[63/123]\n",
      "[64/123]\n",
      "[65/123]\n",
      "[66/123]\n",
      "[67/123]\n",
      "[68/123]\n",
      "[69/123]\n",
      "[70/123]\n",
      "[71/123]\n",
      "[72/123]\n",
      "[73/123]\n",
      "[74/123]\n",
      "[75/123]\n",
      "[76/123]\n",
      "[77/123]\n",
      "[78/123]\n",
      "[79/123]\n",
      "[80/123]\n",
      "[81/123]\n",
      "[82/123]\n",
      "[83/123]\n",
      "[84/123]\n",
      "[85/123]\n",
      "[86/123]\n",
      "[87/123]\n",
      "[88/123]\n",
      "[89/123]\n",
      "[90/123]\n",
      "[91/123]\n",
      "[92/123]\n",
      "[93/123]\n",
      "[94/123]\n",
      "[95/123]\n",
      "[96/123]\n",
      "[97/123]\n",
      "[98/123]\n",
      "[99/123]\n",
      "[100/123]\n",
      "[101/123]\n",
      "[102/123]\n",
      "[103/123]\n",
      "[104/123]\n",
      "[105/123]\n",
      "[106/123]\n",
      "[107/123]\n",
      "[108/123]\n",
      "[109/123]\n",
      "[110/123]\n",
      "[111/123]\n",
      "[112/123]\n",
      "[113/123]\n",
      "[114/123]\n",
      "[115/123]\n",
      "[116/123]\n",
      "[117/123]\n",
      "[118/123]\n",
      "[119/123]\n",
      "[120/123]\n",
      "[121/123]\n",
      "[122/123]\n",
      "[123/123]\n",
      "\n",
      "Listo.\n",
      "Artículos: 123\n",
      "Archivo: heraldo_mexico_migracion_venezolana.csv\n"
     ]
    }
   ],
   "source": [
    "# ============================================================\n",
    "# EL HERALDO DE MÉXICO\n",
    "# Búsqueda: migración venezolana\n",
    "#\n",
    "# Salida:\n",
    "# fecha\n",
    "# autor\n",
    "# pais\n",
    "# medio\n",
    "# titulo\n",
    "# cuerpo\n",
    "# url\n",
    "#\n",
    "# CSV final: heraldo_mexico_migracion_venezolana.csv\n",
    "# ============================================================\n",
    "\n",
    "import re\n",
    "import html\n",
    "import time\n",
    "import requests\n",
    "import pandas as pd\n",
    "\n",
    "from bs4 import BeautifulSoup\n",
    "from urllib.parse import quote_plus, urljoin\n",
    "\n",
    "\n",
    "BUSQUEDA = \"migración venezolana\"\n",
    "\n",
    "BASE_URL = \"https://heraldodemexico.com.mx\"\n",
    "\n",
    "SEARCH_URL = (\n",
    "    \"https://heraldodemexico.com.mx/noticias/buscar/\"\n",
    "    f\"?buscar={quote_plus(BUSQUEDA)}\"\n",
    ")\n",
    "\n",
    "AJAX_URL = (\n",
    "    \"https://heraldodemexico.com.mx/\"\n",
    "    \"a/aps/noticias/paginas/ajax/ultimoinf-fecha-en-grupos.asp\"\n",
    ")\n",
    "\n",
    "HEADERS = {\n",
    "    \"User-Agent\": (\n",
    "        \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) \"\n",
    "        \"AppleWebKit/537.36 (KHTML, like Gecko) \"\n",
    "        \"Chrome/140.0 Safari/537.36\"\n",
    "    )\n",
    "}\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# LIMPIEZA\n",
    "# ============================================================\n",
    "\n",
    "def limpiar_texto(texto):\n",
    "    if not texto:\n",
    "        return \"\"\n",
    "\n",
    "    texto = html.unescape(texto)\n",
    "\n",
    "    texto = re.sub(r\"<[^>]+>\", \" \", texto)\n",
    "    texto = re.sub(r\"(href|src)\\s*=\\s*['\\\"].*?['\\\"]\", \" \", texto, flags=re.I)\n",
    "\n",
    "    texto = re.sub(r\"\\s+\", \" \", texto)\n",
    "\n",
    "    return texto.strip()\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# EXTRAER URLS DESDE HTML DE RESULTADOS\n",
    "# ============================================================\n",
    "\n",
    "def extraer_urls_resultado(html_text):\n",
    "\n",
    "    soup = BeautifulSoup(html_text, \"html.parser\")\n",
    "\n",
    "    urls = set()\n",
    "\n",
    "    for a in soup.select(\"h5.titulo a\"):\n",
    "        href = a.get(\"href\")\n",
    "\n",
    "        if not href:\n",
    "            continue\n",
    "\n",
    "        if href.endswith(\".html\"):\n",
    "            urls.add(urljoin(BASE_URL, href))\n",
    "\n",
    "    for a in soup.select(\"article a\"):\n",
    "        href = a.get(\"href\")\n",
    "\n",
    "        if not href:\n",
    "            continue\n",
    "\n",
    "        if href.endswith(\".html\"):\n",
    "            urls.add(urljoin(BASE_URL, href))\n",
    "\n",
    "    return list(urls)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PAGINA INICIAL\n",
    "# ============================================================\n",
    "\n",
    "def obtener_urls_primera_pagina():\n",
    "\n",
    "    r = requests.get(\n",
    "        SEARCH_URL,\n",
    "        headers=HEADERS,\n",
    "        timeout=60\n",
    "    )\n",
    "\n",
    "    r.raise_for_status()\n",
    "\n",
    "    return extraer_urls_resultado(r.text)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PAGINACIÓN AJAX\n",
    "# ============================================================\n",
    "\n",
    "def obtener_urls_ajax():\n",
    "\n",
    "    todas = set()\n",
    "\n",
    "    page = 1\n",
    "\n",
    "    while True:\n",
    "\n",
    "        payload = {\n",
    "            \"busqueda\": BUSQUEDA,\n",
    "            \"page\": page\n",
    "        }\n",
    "\n",
    "        r = requests.post(\n",
    "            AJAX_URL,\n",
    "            headers=HEADERS,\n",
    "            data=payload,\n",
    "            timeout=60\n",
    "        )\n",
    "\n",
    "        r.raise_for_status()\n",
    "\n",
    "        html_text = r.text\n",
    "\n",
    "        urls = extraer_urls_resultado(html_text)\n",
    "\n",
    "        if not urls:\n",
    "            print(f\"Fin de paginación en page={page}\")\n",
    "            break\n",
    "\n",
    "        nuevas = set(urls) - todas\n",
    "\n",
    "        if not nuevas:\n",
    "            print(f\"Sin URLs nuevas en page={page}\")\n",
    "            break\n",
    "\n",
    "        todas.update(nuevas)\n",
    "\n",
    "        print(\n",
    "            f\"Page {page}: \"\n",
    "            f\"{len(nuevas)} nuevas \"\n",
    "            f\"({len(todas)} acumuladas)\"\n",
    "        )\n",
    "\n",
    "        page += 1\n",
    "\n",
    "        time.sleep(0.5)\n",
    "\n",
    "    return list(todas)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# EXTRAER ARTÍCULO\n",
    "# ============================================================\n",
    "\n",
    "def extraer_articulo(url):\n",
    "\n",
    "    try:\n",
    "\n",
    "        r = requests.get(\n",
    "            url,\n",
    "            headers=HEADERS,\n",
    "            timeout=60\n",
    "        )\n",
    "\n",
    "        r.raise_for_status()\n",
    "\n",
    "        soup = BeautifulSoup(r.text, \"html.parser\")\n",
    "\n",
    "        # -------------------------\n",
    "        # TITULO\n",
    "        # -------------------------\n",
    "\n",
    "        titulo = \"\"\n",
    "\n",
    "        nodo = soup.select_one(\"h1.titulo-noticia\")\n",
    "\n",
    "        if nodo:\n",
    "            titulo = limpiar_texto(nodo.get_text(\" \", strip=True))\n",
    "\n",
    "        if not titulo:\n",
    "            meta = soup.find(\"meta\", {\"property\": \"og:title\"})\n",
    "            if meta:\n",
    "                titulo = limpiar_texto(meta.get(\"content\", \"\"))\n",
    "\n",
    "        # -------------------------\n",
    "        # AUTOR\n",
    "        # -------------------------\n",
    "\n",
    "        autor = \"\"\n",
    "\n",
    "        nodo = soup.select_one(\"span.autor\")\n",
    "\n",
    "        if nodo:\n",
    "            autor = limpiar_texto(\n",
    "                nodo.get_text(\" \", strip=True)\n",
    "            )\n",
    "\n",
    "        if not autor:\n",
    "\n",
    "            m = re.search(\n",
    "                r'\"creador\":\"([^\"]+)\"',\n",
    "                r.text\n",
    "            )\n",
    "\n",
    "            if m:\n",
    "                autor = limpiar_texto(m.group(1))\n",
    "\n",
    "        # -------------------------\n",
    "        # FECHA\n",
    "        # -------------------------\n",
    "\n",
    "        fecha = \"\"\n",
    "\n",
    "        nodo = soup.select_one(\n",
    "            \"span.fecha-de-publicacion\"\n",
    "        )\n",
    "\n",
    "        if nodo:\n",
    "            fecha = limpiar_texto(\n",
    "                nodo.get_text(\" \", strip=True)\n",
    "            )\n",
    "\n",
    "        if not fecha:\n",
    "\n",
    "            m = re.search(\n",
    "                r'\"fecha\":\"([^\"]+)\"',\n",
    "                r.text\n",
    "            )\n",
    "\n",
    "            if m:\n",
    "                fecha = m.group(1)\n",
    "\n",
    "        # -------------------------\n",
    "        # CUERPO\n",
    "        # -------------------------\n",
    "\n",
    "        cuerpo = \"\"\n",
    "\n",
    "        body = soup.select_one(\n",
    "            \"div.texto-noticia\"\n",
    "        )\n",
    "\n",
    "        if body:\n",
    "\n",
    "            parrafos = []\n",
    "\n",
    "            for p in body.find_all(\"p\"):\n",
    "\n",
    "                txt = limpiar_texto(\n",
    "                    p.get_text(\" \", strip=True)\n",
    "                )\n",
    "\n",
    "                if txt:\n",
    "                    parrafos.append(txt)\n",
    "\n",
    "            cuerpo = \"\\n\".join(parrafos)\n",
    "\n",
    "        # -------------------------\n",
    "        # REGISTRO\n",
    "        # -------------------------\n",
    "\n",
    "        return {\n",
    "            \"fecha\": fecha,\n",
    "            \"autor\": autor,\n",
    "            \"pais\": \"México\",\n",
    "            \"medio\": \"El Heraldo de México\",\n",
    "            \"titulo\": titulo,\n",
    "            \"cuerpo\": cuerpo,\n",
    "            \"url\": url\n",
    "        }\n",
    "\n",
    "    except Exception as e:\n",
    "\n",
    "        print(\"ERROR:\", url)\n",
    "        print(e)\n",
    "\n",
    "        return None\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# MAIN\n",
    "# ============================================================\n",
    "\n",
    "print(\"Extrayendo URLs...\")\n",
    "\n",
    "urls = set()\n",
    "\n",
    "urls.update(obtener_urls_primera_pagina())\n",
    "\n",
    "urls.update(obtener_urls_ajax())\n",
    "\n",
    "urls = sorted(urls)\n",
    "\n",
    "print(f\"\\nTotal URLs únicas: {len(urls)}\")\n",
    "\n",
    "# ============================================================\n",
    "# EXTRAER ARTÍCULOS\n",
    "# ============================================================\n",
    "\n",
    "registros = []\n",
    "\n",
    "for i, url in enumerate(urls, start=1):\n",
    "\n",
    "    print(f\"[{i}/{len(urls)}]\")\n",
    "\n",
    "    articulo = extraer_articulo(url)\n",
    "\n",
    "    if articulo:\n",
    "        registros.append(articulo)\n",
    "\n",
    "    time.sleep(0.3)\n",
    "\n",
    "# ============================================================\n",
    "# DATAFRAME\n",
    "# ============================================================\n",
    "\n",
    "df = pd.DataFrame(registros)\n",
    "\n",
    "df = df.drop_duplicates(\n",
    "    subset=[\"url\"]\n",
    ")\n",
    "\n",
    "# ============================================================\n",
    "# CSV\n",
    "# ============================================================\n",
    "\n",
    "archivo_salida = (\n",
    "    \"heraldo_mexico_migracion_venezolana.csv\"\n",
    ")\n",
    "\n",
    "df.to_csv(\n",
    "    archivo_salida,\n",
    "    index=False,\n",
    "    encoding=\"utf-8-sig\"\n",
    ")\n",
    "\n",
    "print(\"\\nListo.\")\n",
    "print(\"Artículos:\", len(df))\n",
    "print(\"Archivo:\", archivo_salida)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
